---
nSpecies: 4

species:
  so2:
    molarMass: 0.64
    heatCapacityModel: polynomial
    enthalpyFormation: -296861.220
    entropyFormation: 248.100
    heatCapacityCoefficients: [3.53]

  o2:
    molarMass: 0.32
    heatCapacityModel: polynomial
    enthalpyFormation: 0.0
    entropyFormation: 205.00
    heatCapacityCoefficients: [3.53]

  n2:
    molarMass: 0.28
    heatCapacityModel: polynomial
    enthalpyFormation: 0.0
    entropyFormation: 191.00
    heatCapacityCoefficients: [3.53]

  so3:
    molarMass: 0.800
    heatCapacityModel: polynomial
    enthalpyFormation: -395782.300
    entropyFormation: 256.6
    heatCapacityCoefficients: [3.53]

reactions:
  - name: so2_conversion
    isReversible: 1
    ahrreniusPreExponent: 50e9
    ahrreniusActivationEnergy: 165000.0

  - name: so2_conversion
    stochiometricCoefficients: [-1.0, -0.5, 0.0, 1.0]
    speciesExponent: [1.0, 0.5, 0.0, 0.0]
    reversedSpecieExponent: [0.0, 0.0, 0.0, 1.0]

mixture:
  densityModel: ideal-incompressible-gas
  densityValue: null